### ISSUE TITLE
Access from UVeditor

### ISSUE THREAD

**Issue by nutti** [nutti/Copy-And-Paste-UV#19]
From @zeauro request at [D.B.O](https://developer.blender.org/T38460).

> Currently, UV editor have a toolbar. Is it possible to give access of this addon tools from UVeditor ?  

> I would like to copy/paste UVs for similar face region selections sets in UV editor.
After an automatic unwrap, Islands would be packed as 2d elements all easily accessible into UVeditor bounds.
But to select your islands into 3D, you may have to pan, to zoom in/ zoom out or rotate around your 3D model.
>
> With synchronization on, there is no difference between selection of face sets in 3Dview and selection of corresponding UV Islands in UV Editor.
>
> And for people that want to use copy/paste into 3Dview, there could be also an addon panel into shading/UVs Tab.

**Comment by nutti** [comment]
@zeauro
Do you want this feature to be added to next version (v4.0)?
If so, I have a question.
Do you say that this add-on should be accessed from UV/Image Editor? If so, how?
This add-on works on **3D View**, so I can not image this merit.
Please tell me more detail.

**Comment by Jimpaw** [comment]
I also think this would be a good function, it would make the script feel a little more complete. I think creating a tab in the left panel with buttons would be great. So lets say yo have splitted a speher in half and put one of the islands where you want it in your uv. You could simply select that and chose "copy" 
and then select the other island and select "paste" and boom you have the two islands stacked over one another.

**Comment by nutti** [comment]
@Jimpaw 

Do you say that new interface should be added to tool-shelf in **3D View**?

**Comment by Jimpaw** [comment]
Hi! 

Here is what i think. Most people that find this kind of script useful probably do 50-100 copy & paste commands on a day. When you repeat things that much you have to streamline the workflow so that every wall in front of the user is removed so that you can work super fast. Inside the uv editor it really makes sence to have most of the commands on a left menu because you will probably don't to most of the work there, but you still want them to be easy to find. 

In the 3d view i think that having a seperate pie menu that only deals with your scripts commands would be the best, but many people like regular menus or panel options aswell. Personally i find panel buttons as a really bad options because they get so crowded fast. If Blender would allow users to customize everything it would be a different cup of tea. I have attached a suggestion of the pie menu. It will require some more programming regarding the flip/rotate command but something like this would make your script lightning fast! 

https://www.dropbox.com/s/6vbdt0mzpr7c5ta/copy_paste_pie_menu_suggestion.jpg?dl=0

**Comment by nutti** [comment]
@Jimpaw 

Link is down your suggestion.

I'm not expert about Pie Menu.
Then, I have a question about your suggestion.
IMO, Pie Menu should be fixed because user want to customize their own style.
However, your suggestion is focused on property of tool-shelf, it is good suggestion.
Is it possible to set property of tool-shelf.

**Comment by Jimpaw** [comment]
i will make a suggestion and post it on your tread in a day or two!

**Comment by nutti** [comment]
Yes sure.

**Comment by nutti** [comment]
This issue no longer needed.
Then, I close it.
